# This file is NOT licensed under the GPLv3, which is the license for the rest
# of Samba.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
'-Wall',
'-Wextra',
'-Werror',
'-Wno-unused-parameter',
# This is a C project
'-x', 'c',
# Defines
'-DHAVE_CONFIG_H'
# System includes
'-I/usr/include',
'-I/usr/include/krb5',
'-I/usr/include/dbus-1.0',
'-I/usr/lib64/dbus-1.0/include',
'-I/usr/include/libnl3',
'-I/usr/include/glib-2.0',
'-I/usr/lib64/glib-2.0/include',
# Project includes
'-I.',
'-I..',
'-Isrc',
'-Isrc/confdb',
'-Isrc/db',
'-Isrc/lib/idmap',
'-Isrc/lib/ipa_hbac',
'-Isrc/lib/sifp',
'-Isrc/lib/winbind_idmap_sss',
'-Isrc/monitor',
'-Isrc/providers',
'-Isrc/providers/ad',
'-Isrc/providers/data_provider',
'-Isrc/providers/ipa',
'-Isrc/providers/krb5',
'-Isrc/providers/ldap',
'-Isrc/providers/proxy',
'-Isrc/providers/simple',
'-Isrc/resolv',
'-Isrc/responder/autofs',
'-Isrc/responder/common',
'-Isrc/responder/common/cache_req',
'-Isrc/responder/common/data_provider',
'-Isrc/responder/ifp',
'-Isrc/responder/kcm',
'-Isrc/responder/nss',
'-Isrc/responder/pac',
'-Isrc/responder/pam',
'-Isrc/responder/secrets',
'-Isrc/responder/ssh',
'-Isrc/responder/sudo',
'-Isrc/sbus',
'-Isrc/sss_client',
'-Isrc/sss_client/autofs',
'-Isrc/sss_client/idmap',
'-Isrc/sss_client/libwbclient',
'-Isrc/sss_client/nfs',
'-Isrc/sss_client/ssh',
'-Isrc/sss_client/sudo',
'-Isrc/tests',
'-Isrc/tests/cmocka',
'-Isrc/tests/cmocka/data_provider',
'-Isrc/tools',
'-Isrc/tools/common',
'-Isrc/tools/sssctl',
'-Isrc/util',
'-Isrc/util/crypto',
'-Isrc/util/crypto/libcrypto',
'-Isrc/util/crypto/nss',
]

# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )
  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }
